-- MySQL Script generated by MySQL Workbench
-- Tue Feb 25 19:39:21 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema restaurants
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema restaurants
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `restaurants` DEFAULT CHARACTER SET utf8 ;
USE `restaurants` ;

-- -----------------------------------------------------
-- Table `restaurants`.`areas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurants`.`areas` (
  `idareas` INT NOT NULL AUTO_INCREMENT,
  `name_area` VARCHAR(45) NULL,
  PRIMARY KEY (`idareas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurants`.`cousine_style`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurants`.`cousine_style` (
  `idcousine_style` INT NOT NULL AUTO_INCREMENT,
  `style` VARCHAR(45) NULL,
  PRIMARY KEY (`idcousine_style`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurants`.`restaurant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurants`.`restaurant` (
  `idrestaurant` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `cousine_style` VARCHAR(45) NULL,
  `area` VARCHAR(45) NULL,
  `price_range` DECIMAL(4,2) NULL,
  `fk_areas` INT NOT NULL,
  `fk_cousine_style` INT NOT NULL,
  PRIMARY KEY (`idrestaurant`),
  INDEX `fk_restaurants_areas_idx` (`fk_areas` ASC) VISIBLE,
  INDEX `fk_restaurants_cousine_style1_idx` (`fk_cousine_style` ASC) VISIBLE,
  CONSTRAINT `fk_restaurants_areas`
    FOREIGN KEY (`fk_areas`)
    REFERENCES `restaurants`.`areas` (`idareas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_restaurants_cousine_style1`
    FOREIGN KEY (`fk_cousine_style`)
    REFERENCES `restaurants`.`cousine_style` (`idcousine_style`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
